import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
      <body className={inter.className}>
      <nav className="p-10 flex gap-20 text-4xl text-center font-bold bg-gray-500 color-white">
        <Link href="/">Home</Link>
        <Link href="/catalog">List</Link>
        <Link href="/reviews">Reviews</Link>
      </nav>
      <main className="flex min-h-screen flex-col justify-between p-32">
        {children}
      </main>
      </body>
      </html>
  );
}
